### ISSUE TITLE
Unable to load the mojo 'build'

### ISSUE THREAD

**Issue by stlecho** [chrisdchristo/capsule-maven-plugin-demo#2]
I've downloaded the project, but when I run it I get the following error:

[ERROR] Failed to execute goal com.github.chrischristo:capsule-maven-plugin:0.10.8:build (default) on project capsule-maven-plugin-demo: Execution default of goal com.github.chrischristo:capsule-maven-plugin:0.10.8:build failed: Unable to load the mojo 'build' (or one of its required components) from the plugin 'com.github.chrischristo:capsule-maven-plugin:0.10.8': com.google.inject.ProvisionException: Guice provision errors:
[ERROR] 
[ERROR] 1) No implementation for org.eclipse.aether.RepositorySystem was bound.
[ERROR] while locating capsule.CapsuleBuildMojo
[ERROR] at ClassRealm[plugin>com.github.chrischristo:capsule-maven-plugin:0.10.8, parent: sun.misc.Launcher$AppClassLoader@4e25154f]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=com.github.chrischristo:capsule-maven-plugin:0.10.8:build)

**Comment by chrischristo** [comment]
You need to have a newer version of Maven, 3.1+. Have a look at the requirements on the capsule maven plugin page.

**Comment by stlecho** [comment]
I've tried with maven 3.2.5 which is not working, but with maven 3.3.3 it works. Tx for your help.
